config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

  resources :users do
      member do
          get 'favorite'
      end
  end

  resources :microposts
  resources :relationships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  
   resources :favorites, only: [:create,:destroy]

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
    belongs_to :user, class_name: "User"
    belongs_to :micropost, class_name: "Micropost"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
   has_many :favorite_favorites, class_name: "Favorite",
                                 foreign_key: "micropost_id",
                                 dependent: :destroy
    has_many :favorite_users, through: :favorite_favorites, source: :user
    
     
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :microposts
    
   
    has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    
    has_many :favorited_favorites, class_name: "Favorite",
                                 foreign_key: "user_id",
                                 dependent: :destroy
    has_many :favorited_microposts, through: :favorited_favorites, source: :micropost
    
  
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.create(followed_id: other_user.id)
    end

    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationships.find_by(followed_id: other_user.id).destroy
    end

    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
    
   #他のユーザーの記事をお気に入りにする
    def favorite(micropost)
        favorited_favorites.create(micropost_id: micropost.id)
    end
    
    #お気に入りの記事をお気に入りから外す
    def unfavorite(micropost)
        favorited_favorites.find_by(micropost_id: micropost.id).destroy
    end
    
    #ある記事がお気に入りされているかどうか
    def favoriting?(micropost)
        favorited_microposts.include?(micropost)
    end
        
end

 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :logged_in_user
    
    def create
        @micropost = Micropost.find(params[:micropost_id])
        current_user.favorite(@micropost)
    end

    def destroy
        if @micropost = Favorite.find(params[:id]).micropost
            current_user.unfavorite(@micropost)
        end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
     before_action :logged_in_user, only: [:create]


  def create
    @micropost = current_user.microposts.build(micropost_params)
    @user = @micropost.user

    if @micropost.save
      
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_logined, only: :show
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session] [:email].downcase)
    if @user && @user.authenticate(params[:session] [:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build 
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(6)
    end
    
     
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def show #追加
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page]).per(6)
   
  end
  
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'Profileを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
      @user.save
    end
  end
  
   def favorite
    @user = User.find(params[:id])
    @favorited_microposts = @user.favorited_microposts
    @favorited_favorites = @user.favorited_favorites
   
  end
    
  private
    
  def user_params
    params.require(:user).permit(:avatar,:avatar_cache,:name,:area, :email, :password,
                                   :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/favorites/create.js.erb
$("#favorite_form-<%= @micropost.id %>").html("<%= escape_javascript(render('users/unfavorite')) %>");

app/views/favorites/destroy.js.erb
$("#favorite_form-<%= @micropost.id %>").html("<%= escape_javascript(render('microposts/favorite')) %>");

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
      
      <% flash.each do |message_type, message| %><!-- ここから -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> <!-- ここまで追加 -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_favorite.html.erb
 <%= form_for(@micropost.favorite_favorites.build, remote: true) do |f| %>
      <div><%= hidden_field_tag :micropost_id, @micropost.id %></div>
      <%= f.submit "Favorite", class: "btn btn-primary" %>
   
<% end %>

app/views/microposts/_micropost.html.erb
<% @micropost = micropost %>
<li id="micropost-<%= micropost.id %>">
  <%= image_tag(micropost.user.avatar,:size =>"40") %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
 
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% else %>
      <%= render 'users/favorite_form' %>
    <% end %>
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.follower_users.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.follower_users.count %>');

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count,"error") %>
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>    
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
   
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= image_tag(current_user.avatar,:size =>"100") %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_favorite_form.html.erb
<div id="favorite_form-<%= @micropost.id %>">
  <% if current_user.favoriting?(@micropost) %>
    <%= render 'users/unfavorite' %>
  <% else %>
    <%= render 'microposts/favorite' %>
  <% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfavorite.html.erb
<%= form_for(@micropost.favorite_favorites.find_by(user_id: current_user.id),
                html: { method: :delete },
                remote: true) do |f| %>
    <%= f.submit "Unfavorite", class: "btn" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
      <%= image_tag @user.avatar.url if @user.avatar %>
      
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
      
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :area %>
      <%= f.text_field :area %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      

      <%= f.submit "Update my account", class: "btn btn-lg btn-primary " %>
    <% end %>
  </div>
</div>

app/views/users/favorite.html.erb
<%  @favorited_microposts.each do |micropost| %>
    <%= image_tag(micropost.user.avatar) %>
    <%= micropost.content %>
    <hr>
<% end %>

app/views/users/followers.html.erb
<% @followers.each do |follower| %>
   <p><%= gravatar_for(@user, size: 40) %>
   <span><%= link_to follower.name  , user_path(follower) %></span></p>
   <br>
<% end %>

app/views/users/following.html.erb
<% @following.each do |follow| %>
  <p><%= gravatar_for(@user, size: 40) %>
  <span><%= link_to follow.name  , user_path(follow) %></span></p>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
        <%= image_tag(@user.avatar) %>
        <h1><%= @user.name %></h1>
     

    </section>
    <section class="user_profile">
     <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      Name: <%= @user.name %>
      <br>
      Area: <%= @user.area %>
      
      
      <% if @user == current_user %><br />
      <%= link_to "Edit Profile", edit_user_path(current_user) , class: "btn  btn-primary btn-block" %>

      <% end %>

      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <!-- タブ・メニュー -->
    <ul class="nav nav-pills">
	    <li class="active"><a href="#Tweet" data-toggle="tab">Tweet</a></li>
    	<li><a href="#Favorite" data-toggle="tab">Favorite</a></li>
    </ul>
    <!-- ここまでがタブ・メニュー -->

    <!-- タブ内容 -->
    <div class="tab-content">
      <!-- ツイートのコンテンツ部分 -->
    	<div class="tab-pane active" id="Tweet">
    	  <%= render 'follow_form' if logged_in? %>
          <% if @user.microposts.any? %>
            <h3>Microposts(<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
            <%= render @microposts %>
            <%= paginate @microposts %>
            </ol>
          <% end %>
      </div>
      <!-- ここまでがツイートのコンテンツ部分 -->
      
      <!-- お気に入りのコンテンツ部分 -->
	    <div class="tab-pane" id="Favorite">
	      <h3>Favorites(<%= @user.favorited_microposts.count %>)</h3>
	      <hr>
	       <%  @user.favorited_microposts.each do |micropost| %>
          <%= image_tag(micropost.user.avatar) %>
          <%= micropost.content %>
        <hr>
        <% end %>
	    </div>
	    <!-- ここまでがお気に入りのコンテンツ部分 -->
    </div>
    <!-- ここまでがタブ内容 -->
    
  </div>
</div>